baseURL = "https://localhost:1313/"
languageCode = "en-us"
title = "TESCO - The Eastern Specialty Company"
theme = "hugo-book"

[taxonomies]
  risk = 'risks'
  level = 'levels'

[params]
  company = 'TESCO - The Eastern Specialty Company'
  csor = 'SDLC'
  vcs = 'git'
  vcsHost = 'github'
  forkLink = 'https://github.com/kosli-dev/devopsctl/fork'
  logo = 'svg/logo.png'
  BookSection = '/'

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 3